version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vKb2Xn!!kM94BR
      POSTGRES_DB: luxmed
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - luxmed-network

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - luxmed-network

volumes:
  postgres-data:

networks:
  luxmed-network:
